### ISSUE TITLE
Auto-auth proxy

### ISSUE THREAD

**Issue by simontaurus** [opensemanticworld/caddy-docker-proxy#1]
Untested:

```yaml
    labels:
      caddy: autoauth.api.<domain>
      caddy.reverse_proxy: http://finales:13371
      caddy.header: +Authorization "Bearer <token>"
      caddy.header_01: Access-Control-Allow-Origin *
      caddy.header_02: Access-Control-Request-Method *
```
